### ISSUE TITLE
768px < width < 990px, .navbar-nav 跑版

### ISSUE THREAD

**Issue by Rplus** [jsdc-core/jsdc2017#5]
晚進來的 FB like 按鈕把 nav 寬度撐開了，於是就換行了 XD
![image](https://user-images.githubusercontent.com/1808835/30010358-c4c9897a-9161-11e7-87d6-0e1d0ac8bc88.png)

**Comment by IvanWei** [comment]
fix it ([e587167](https://github.com/jsdc-core/jsdc2017/commit/e587167b05499bfaf93a76597bb7f9aabf23ee22))

**Comment by Rplus** [comment]
😭  我以為會是調整 Like button 的設計 XDD

**Comment by IvanWei** [comment]
主要是 Navbar 還有2 頁還沒顯示 :p 
之後再找時間加工 XD
